"use client";

import { useMemo, useState } from "react";
import { motion } from "framer-motion";
import {
  History,
  Search,
  Eye,
  Download,
  Trash2,
} from "lucide-react";

import { ReportAPI, type Report } from "@/lib/reports";

interface ReportHistoryProps {
  reports: Report[];
  loading: boolean;
  onDelete: (id: number) => Promise<void>;
}

export default function ReportHistory({
  reports,
  loading,
  onDelete,
}: ReportHistoryProps) {

  const [search, setSearch] = useState("");

  const filteredReports = useMemo(() => {
    const q = search.toLowerCase();

    return reports.filter((report) =>
      report.title.toLowerCase().includes(q) ||
      report.report_type.toLowerCase().includes(q) ||
      report.generated_by.toLowerCase().includes(q)
    );
  }, [reports, search]);

  if (loading) {
    return (
      <div className="rounded-3xl border border-white/10 bg-slate-900/70 p-6 text-white">
        Loading reports...
      </div>
    );
  }

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="rounded-3xl border border-white/10 bg-slate-900/70 p-6"
    >

      <div className="mb-6 flex items-center justify-between">

        <div>
          <h2 className="text-2xl font-bold text-white">
            Report History
          </h2>

          <p className="text-slate-400">
            Reports stored in the backend
          </p>
        </div>

        <div className="relative">

          <Search
            size={18}
            className="absolute left-3 top-3 text-slate-500"
          />

          <input
            value={search}
            onChange={(e) =>
              setSearch(e.target.value)
            }
            placeholder="Search..."
            className="rounded-xl border border-slate-700 bg-slate-800 py-2 pl-10 pr-4 text-white outline-none focus:border-sky-500"
          />

        </div>

      </div>

      <div className="overflow-x-auto">

        <table className="w-full">

          <thead>

            <tr className="border-b border-slate-700 text-left text-slate-400">

              <th className="py-3">
                Title
              </th>

              <th>
                Type
              </th>

              <th>
                Generated By
              </th>

              <th>
                Created
              </th>

              <th className="text-right">
                Actions
              </th>

            </tr>

          </thead>

          <tbody>
                        {filteredReports.length === 0 ? (
              <tr>
                <td
                  colSpan={5}
                  className="py-10 text-center text-slate-400"
                >
                  No reports found.
                </td>
              </tr>
            ) : (
              filteredReports.map((report) => (
                <tr
                  key={report.id}
                  className="border-b border-slate-800 hover:bg-slate-800/40 transition"
                >
                  <td className="py-4">
                    <div>
                      <p className="font-semibold text-white">
                        {report.title}
                      </p>

                      <p className="text-xs text-slate-500">
                        {report.file_name}
                      </p>
                    </div>
                  </td>

                  <td>
                    <span className="rounded-full bg-sky-500/10 px-3 py-1 text-xs font-medium text-sky-300">
                      {report.report_type}
                    </span>
                  </td>

                  <td className="text-slate-300">
                    {report.generated_by}
                  </td>

                  <td className="text-slate-300">
                    {new Date(
                      report.created_at
                    ).toLocaleString()}
                  </td>

                  <td>
                    <div className="flex justify-end gap-2">

                      {/* Preview */}
                      <button
                        onClick={() =>
                          ReportAPI.preview(report.id)
                        }
                        className="rounded-lg bg-slate-800 p-2 transition hover:bg-slate-700"
                      >
                        <Eye
                          size={16}
                          className="text-sky-400"
                        />
                      </button>

                      {/* Download */}
                      <button
                        onClick={() =>
                          ReportAPI.download(report.id)
                        }
                        className="rounded-lg bg-slate-800 p-2 transition hover:bg-slate-700"
                      >
                        <Download
                          size={16}
                          className="text-emerald-400"
                        />
                      </button>

                      {/* Delete */}
                      <button
                        onClick={async () => {
                          if (
                            !confirm(
                              "Delete this report?"
                            )
                          )
                            return;

                          try {
                            await onDelete(report.id);
                          } catch (err) {
                            console.error(err);
                          }
                        }}
                        className="rounded-lg bg-red-600 p-2 transition hover:bg-red-700"
                      >
                        <Trash2
                          size={16}
                          className="text-white"
                        />
                      </button>

                    </div>
                  </td>
                </tr>
              ))
            )}
          </tbody>

        </table>

      </div>

      {/* Footer */}

      <div className="mt-6 flex items-center justify-between border-t border-slate-800 pt-4">

        <div className="flex items-center gap-2 text-slate-400">

          <History size={18} />

          <span>
            Showing{" "}
            <span className="font-semibold text-white">
              {filteredReports.length}
            </span>{" "}
            report
            {filteredReports.length !== 1
              ? "s"
              : ""}
          </span>

        </div>

        <button
          onClick={() => window.scrollTo({
            top: 0,
            behavior: "smooth",
          })}
          className="rounded-xl border border-slate-700 px-4 py-2 text-sm text-slate-300 transition hover:border-sky-500 hover:text-white"
        >
          Back to Top
        </button>

      </div>

    </motion.div>
  );
}