import os
import re

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
)

from reportlab.lib.styles import getSampleStyleSheet


REPORT_FOLDER = "reports"

os.makedirs(REPORT_FOLDER, exist_ok=True)


def generate_pdf(
    title: str,
    report_type: str,
    generated_by: str,
):
    # Remove invalid Windows filename characters
    safe_title = re.sub(
        r'[\\/:*?"<>|]',
        "_",
        title,
    )

    filename = (
        safe_title.replace(" ", "_")
        + ".pdf"
    )

    path = os.path.join(
        REPORT_FOLDER,
        filename,
    )

    styles = getSampleStyleSheet()

    doc = SimpleDocTemplate(path)

    elements = []

    elements.append(
        Paragraph(
            title,
            styles["Title"],
        )
    )

    elements.append(
        Spacer(1, 20)
    )

    elements.append(
        Paragraph(
            f"<b>Report Type:</b> {report_type}",
            styles["BodyText"],
        )
    )

    elements.append(
        Paragraph(
            f"<b>Generated By:</b> {generated_by}",
            styles["BodyText"],
        )
    )

    elements.append(
        Paragraph(
            "<b>Status:</b> Completed",
            styles["BodyText"],
        )
    )

    elements.append(
        Spacer(1, 30)
    )

    elements.append(
        Paragraph(
            """
            This report was automatically generated by AirGuardian AI.

            It contains environmental monitoring,
            industrial safety analysis,
            AI recommendations,
            and compliance information.
            """,
            styles["BodyText"],
        )
    )

    doc.build(elements)

    return filename