from sqlalchemy.orm import Session

from fastapi import (
    APIRouter,
    Depends,
    HTTPException,
)

from fastapi.responses import (
    FileResponse,
    StreamingResponse,
)

import os
import csv
import io

from app.core.database import get_db
from app.core.security import get_current_user

from app.models.user import User
from app.models.report import Report

from app.schemas.report import (
    ReportCreate,
    ReportResponse,
)

from app.utils.pdf_generator import generate_pdf


router = APIRouter(
    prefix="/reports",
    tags=["Reports"],
)


# ---------------------------------
# Get All Reports
# ---------------------------------
@router.get(
    "/",
    response_model=list[ReportResponse],
)
def get_reports(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    return (
        db.query(Report)
        .order_by(Report.created_at.desc())
        .all()
    )


# ---------------------------------
# Generate Report
# ---------------------------------
@router.post(
    "/generate",
    response_model=ReportResponse,
)
def generate_report(
    report: ReportCreate,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    filename = generate_pdf(
        report.title,
        report.report_type,
        current_user.full_name,
    )

    new_report = Report(
        title=report.title,
        report_type=report.report_type,
        generated_by=current_user.full_name,
        file_name=filename,
    )

    db.add(new_report)
    db.commit()
    db.refresh(new_report)

    return new_report
# ---------------------------------
# Preview Report
# ---------------------------------
@router.get("/{report_id}/preview")
def preview_report(
    report_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    report = (
        db.query(Report)
        .filter(Report.id == report_id)
        .first()
    )

    if report is None:
        raise HTTPException(
            status_code=404,
            detail="Report not found",
        )

    path = os.path.join(
        "reports",
        report.file_name,
    )

    if not os.path.exists(path):
        raise HTTPException(
            status_code=404,
            detail="PDF file not found",
        )

    return FileResponse(
        path,
        media_type="application/pdf",
    )


# ---------------------------------
# Download Report
# ---------------------------------
@router.get("/{report_id}/download")
def download_report(
    report_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    report = (
        db.query(Report)
        .filter(Report.id == report_id)
        .first()
    )

    if report is None:
        raise HTTPException(
            status_code=404,
            detail="Report not found",
        )

    path = os.path.join(
        "reports",
        report.file_name,
    )

    if not os.path.exists(path):
        raise HTTPException(
            status_code=404,
            detail="PDF file not found",
        )

    return FileResponse(
        path,
        media_type="application/pdf",
        filename=report.file_name,
    )


# ---------------------------------
# Delete Report
# ---------------------------------
@router.delete("/{report_id}")
def delete_report(
    report_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    report = (
        db.query(Report)
        .filter(Report.id == report_id)
        .first()
    )

    if report is None:
        raise HTTPException(
            status_code=404,
            detail="Report not found",
        )

    path = os.path.join(
        "reports",
        report.file_name,
    )

    if os.path.exists(path):
        os.remove(path)

    db.delete(report)
    db.commit()

    return {
        "message": "Report deleted successfully"
    }
# ---------------------------------
# Export Reports as CSV
# ---------------------------------
@router.get("/export/csv")
def export_csv(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    reports = (
        db.query(Report)
        .order_by(Report.created_at.desc())
        .all()
    )

    output = io.StringIO()
    writer = csv.writer(output)

    writer.writerow([
        "ID",
        "Title",
        "Report Type",
        "Generated By",
        "File Name",
        "Created At",
    ])

    for report in reports:
        writer.writerow([
            report.id,
            report.title,
            report.report_type,
            report.generated_by,
            report.file_name,
            report.created_at,
        ])

    output.seek(0)

    return StreamingResponse(
        iter([output.getvalue()]),
        media_type="text/csv",
        headers={
            "Content-Disposition":
            "attachment; filename=reports.csv"
        },
    )


# ---------------------------------
# Export Reports as JSON
# ---------------------------------
@router.get("/export/json")
def export_json(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    reports = (
        db.query(Report)
        .order_by(Report.created_at.desc())
        .all()
    )

    return [
        {
            "id": report.id,
            "title": report.title,
            "report_type": report.report_type,
            "generated_by": report.generated_by,
            "file_name": report.file_name,
            "created_at": report.created_at,
        }
        for report in reports
    ]


# ---------------------------------
# Export Reports as ZIP
# ---------------------------------
@router.get("/export/zip")
def export_zip(
    current_user: User = Depends(get_current_user),
):
    raise HTTPException(
        status_code=501,
        detail="ZIP export is not implemented yet.",
    )